# Generated by Django 2.2 on 2022-01-03 09:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 1, 3, 15, 10, 33, 821630))),
                ('body', models.TextField(default='', max_length=1000)),
                ('url', models.TextField(default='', max_length=1000)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('icon', models.ImageField(default='', upload_to='images/')),
                ('votes_total', models.IntegerField(default=1)),
                ('hunter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
